name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: todolist
          MYSQL_ROOT_PASSWORD: ""  # Set to blank
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow empty password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            mysqladmin ping -h127.0.0.1 -uroot && break || sleep 2;  # No password provided
          done

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          MYSQL_DATABASE: "todolist"
          MYSQL_ROOT_PASSWORD: ""  # Set to blank
          MYSQL_USER: "root"
          MYSQL_PASSWORD: ""  # Set to blank
